### ISSUE TITLE
Display of confidence values

### ISSUE THREAD

**Issue by lczech** [cmzmasek/forester#14]
Hi @cmzmasek,

currently, @jhcepas, @stamatak and I are working on an update to our article on the [incorrect mapping of support values after tree rooting](http://biorxiv.org/content/early/2015/12/25/035360). 

Archaeopteryx (and therefore forester) is one of the few tree viewers that correctly supports the distinction between values that belong to inner nodes vs those that belong to edges of the tree. Well done! This is particularly an issue when reading Newick files (as there is no distinction in the format), and can most easily be observed when rerooting the tree - see the article for details.

However, there is one issue that we assume to be a bug: In the section “Display Data” of Archaeopteryx, there is an option "Confidence Values", which however does not display the confidence values, but only shows them when hovering the mouse over a node. Is this behaviour intended?
(This assumes that the option “Internal Node Names are Confidence Values” is checked, as described in the [manual](https://sites.google.com/site/cmzmasek/home/software/archaeopteryx/documentation#TOC-Internal-Node-Names-are-Confidence-Vales).)

If this is not the intention, do you want to fix this? We would be happy to include this as an update to our article.

Edit: We also reported the behaviour of ATV, and found that different versions of it seem to switch between interpreting inner values as belonging to nodes or edges. As far as I could figure it out, ATV is no longer maintained, so we might just drop it from the article. What do you suggest?

Thanks
Lucas

**Comment by cmzmasek** [comment]
Thank you for your comment.
Did you check “Internal Node Names are Confidence Values" before reading the NH formatted tree?

**Comment by lczech** [comment]
Hi @cmzmasek,

yes, I checked this box before reading the file.

Here is how it looks:
![screenshot](https://cloud.githubusercontent.com/assets/4741887/16301520/151aeb5a-3946-11e6-8fb8-f40ab847c486.png)

The "2" in a box is a tool tip hovering where the mouse is. The other support values are not visible.
The tree is

    ((C,D)1,(A,(B,X)3)2,E);

running Archaeopteryx 0.9901 beta on Ubuntu 14.04.

Lucas

**Comment by cmzmasek** [comment]
Hi, @lczech
I see. Please download the newest version (0.9911, just released today). it fixes this problem.
https://sites.google.com/site/cmzmasek/home/software/archaeopteryx
-Chris-

**Comment by lczech** [comment]
Hi Chris,
thanks for fixing this, works now.

Remark: As you see in the picture, re-rooting the tree doubles ones of the confidence values (the left-most one is superfluous). This is not totally bad - at least the other ones are correct. You might however consider leaving this spot empty instead.
![arfix](https://cloud.githubusercontent.com/assets/4741887/16328694/e17947f0-39dc-11e6-8668-7f52df75868b.png)

Furthermore, Archaeopteryx now expects Java 1.8 ( = Java 8 = Java 52, if I understand their weird versioning correctly). Thus, at first I got an `java.lang.UnsupportedClassVersionError`, because this is not the default Java version of Ubuntu (currently). If possible, for user convenience, you might consider compiling with the `-target 1.7` option. See http://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-version

Best
Lucas
