### ISSUE TITLE
Release forester to Maven Central repository

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cmzmasek/forester#7]
```
Hi, any plans to release forester to the Maven central repository 
(search.maven.org)? 

If so, I could volunteer to help :)

Thanks!
Bruno
```

Original issue reported on code.google.com by `brunodep...@gmail.com` on 18 Jun 2014 at 11:46

**Comment by cmzmasek** [comment]
Thank you for your suggestion and offer, but I currently have no plans to release forester to the Maven central repository.
